language: node_js
node_js:
  - '12.16.3'

cache:
  directories:
    - "node_modules"

script:
  - ttsc
  - npm run bundle:prod
  - echo my-custom-domain.ru > build/CNAME

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  repo: franzzua/solid-context
  target-branch: master
  on:
    branch: master