# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16 # optional, default is 10.x


    # Runs a single command using the runners shell
    - name: Install deps
      run: |
        npm i pnpm -g
        pnpm i

    - name: cache nodemodules
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-primes
      
    # Runs a single command using the runners shell
    - name: Build typescript
      run: npx ttsc

    # Runs a set of commands using the runners shell
    - name: Bundle production
      run: npm run bundle:prod

    - name: deploy to solid
      run: node publish.js
